### ISSUE TITLE
step failure

### ISSUE THREAD

**Issue by rvowles** [dart-ogurets/Ogurets#10]
if a step fails, it may not create a step failure properly, particularly if there are missing params.

try {
          if (scenarioStatus.failed) {
            stepStatus.skipped = true;
          } else {
            // to actually run the step
            await state.stepRunners[found](params, moreParams, scenarioSession, scenarioStatus, stepStatus);
          }
        } catch (e, s) {
          _log.severe("Step failed: $step", e, s);
// if failure is empty then set this. Also StepFailure expects a string, so ensure it can take anything and turn it into a string
          **stepStatus.failure = StepFailure(e, s);**
        } finally {
          if (!stepStatus.failed && !scenarioStatus.failed) {
            scenarioStatus.passedSteps.add(stepStatus);
          }
          state.fmt.done(stepStatus);
        }
      }

**Comment by tobindh** [comment]
This is resolved by #15.  Final implementation is:

 catch (e, s) {
          _log.fine("Step failed: $step");
          // if we get here and it's not set as failed, make sure to set it.
          // this can happen if there are runtime constructor issues on the step class construction, for example
          if(!stepStatus.failed)
          {
            stepStatus.failure = StepFailure(e, s.toString());
          }
        } finally {
          if (!stepStatus.failed && !scenarioStatus.failed) {
            scenarioStatus.passedSteps.add(stepStatus);
