### ISSUE TITLE
Trying to access scenario failures results in an error

### ISSUE THREAD

**Issue by tobindh** [dart-ogurets/Ogurets#14]
Attempting access failures in ScenarioStatus results in the following error because of attempting to return a List<BufferedStatus> as a List<StepStatus>, and can't implicitly cast:

_TypeError (type 'List<BufferedStatus>' is not a subtype of type 'List<StepStatus>')

**Comment by rvowles** [comment]
This looks like you are writing that new reporter :-)

**Comment by tobindh** [comment]
Any chance you could look at #15?

**Comment by tobindh** [comment]
Fixed with #15
