### ISSUE TITLE
Support for null safety

### ISSUE THREAD

**Issue by SAGARSURI** [dart-ogurets/Ogurets#18]
Hey @rvowles ,

Great job on this plugin! We are heavily using it in our flutter project. I would like to know when you guys are releasing the null safe version?

Thanks
Sagar

**Comment by rvowles** [comment]
I just pushed null safety for core ogurets. You mean the ogurets flutter as well?

**Comment by SAGARSURI** [comment]
Wow, that's amazing! No not the flutter one. I am using the core package only. Hoping to see a new version in pub.dev soon. Thanks again @rvowles

**Comment by rvowles** [comment]
It needs some further testing which I'm doing on my and @IrinaSouth 's own project. If you clone this repo and change your dependency to a path you would be able to try it out and provide feedback.

**Comment by rvowles** [comment]
this is now published, i expect there will possibly be some issues from it and i will provide rapid support for it.
