### ISSUE TITLE
Cannot navigate between scenarios steps and it's declaration in IDE

### ISSUE THREAD

**Issue by stereotype013** [dart-ogurets/Ogurets#9]
Hello, 
thank you for your job, it's very useful. I'm not sure that this question is for you, but I am used to go fast and comfortable between gherkin scenario lines and step definitions in IDE, but it's not possible with your plugin or any other. Please help if you now the solution. Excuse for troubling!

**Comment by IrinaSouth** [comment]
Hi there, glad to hear you found the plugin useful. You should be able to navigate from feature file step to the step definition (cmd+enter).  If you are unable to do this could you please provide some details - version of the IDE and also screenshot if possible of the feature/scenario file and a step definition implementation. Thank you

**Comment by rvowles** [comment]
I also suspect this is an issue for the IntelliJ repository plugin? as in here? https://github.com/dart-ogurets/OguretsIntellij/issues

**Comment by rvowles** [comment]
please re-open on the Ogurets github if there is still an issue?
